### ISSUE TITLE
Contributing Glyphs?

### ISSUE THREAD

**Issue by whatsnewsisyphus** [theleagueof/league-spartan#1]
Hello,
I was wondering if you were taking glyph contributions and if so, what format you would like them. I'd like to add Kurdish and Turkish letters. You have the components for most of them anyhow, like you have ç but not ş.

**Comment by micahbrich** [comment]
@whatsnewsisyphus Yes, totally! Just make a fork, make sure you're saving UFO, and then we should be able to do it a with a pull request. I'd love that.

**Comment by whatsnewsisyphus** [comment]
What editor did you use? The ufo file cannot be opened in Fontforge or Robofont

**Comment by whatsnewsisyphus** [comment]
https://github.com/whatsnewsisyphus/league-spartan/commit/abc7ef4a4890abece5f030cf1c69cc827b1ba701

Just grab the glyphs from there, I'm not pushing because my typeeditor messed up the timezones and touched a couple other glyphs that I did not manipulate upon saving, I'm not sure why or what it did.

**Comment by whatsnewsisyphus** [comment]
https://github.com/whatsnewsisyphus/league-spartan/commit/db634f4f6f57965a1f09c16294fbde258b1fed70

Just grab the glyphs from there, I'm not pushing because my typeeditor messed up the timezones and touched a couple other glyphs that I did not manipulate upon saving, I'm not sure why or what it did. Also, I wasn't sure if you wanted cedillas to be a separate outline so I did not merge them with the letter outline, you can do that with a single click since they are overlaying with correct contour direction

**Comment by sursly** [comment]
Just a head's up, this will be solved with the new version of League Spartan (coming very soon).

**Comment by elioqoshi** [comment]
@sursly When is that coming out? Any news?

**Comment by micahbrich** [comment]
@elioqoshi we're working on a few different things at once, but trying to get some new releases out once we have a new website that we can update more easily 🙌

**Comment by elioqoshi** [comment]
Can we help somehow? :D

**Comment by alerque** [comment]
We *are* taking glyph submissions. As of now we're in a position we could review and potentially include any source contributions.

At the moment the canonical source format is Glyphs. However if you'd like to work in a different editor we can accommodate almost anything, but please git in touch about the process first because it's a bit complicated to submit glyphs to a variable font project in a different source format. Not impossible just complicated. We're working on making the process seamless using Fontship but it's not there yet. If it isn't Glyphs, open an issue with what you want to contribute and from what editor and we'll work out how before you get too far in.

In the mean time I am going to close this issue because I think the original request for Turkish characters from @whatsnewsisyphus is already covered by the newest release. En azından Türkçe için gereken harfler bulunuyor artık. Kürtçeye gelince alfabesini bilmiyorum ama kapsamıyorsa lütfen yeni issue açın.

**Comment by whatsnewsisyphus** [comment]
Thank you caleb. Ill check the Glyph table. Kurdish(latin) uses A, Ê, Î, O
and Û. I can open an issue if they are not there.

Have a lovely week

**Comment by alerque** [comment]
A and O are part of the English Latin set anyway, I assume you mean `âêîô ÂÊÎÔ`. I think you'll find they are all there:

![image](https://user-images.githubusercontent.com/173595/91722718-5666dd80-eba3-11ea-89f7-5d506f1624e2.png)

**Comment by whatsnewsisyphus** [comment]
Oh interesting, mail to github must have sterilized the letter somehow, yes
that is what I meant. Thanks for the quick response. You are all set for
Kurdish!

Have a lovely one
